name: CI Pipeline

on:
  push:
    branches: [main, development, release/**]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies directly
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем только необходимые пакеты напрямую
        pip install pytest
        
    - name: Run tests
      run: |
        python tests/test_units.py
        python tests/test_integration.py
        python run_tests.py

  documentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate simple documentation
      run: |
        echo "# Automated Documentation" > DOCUMENTATION.md
        echo "## Generated: $(date)" >> DOCUMENTATION.md
        echo "## Project Files:" >> DOCUMENTATION.md
        find . -maxdepth 2 -type f -name "*.py" -o -name "*.md" -o -name "*.yml" | sort >> DOCUMENTATION.md
        
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: DOCUMENTATION.md
        retention-days: 5
